### So now you have understood how decision tree works now it's your time to practice it

### **Import all the required libraries.**

In [96]:
import numpy as np
import pandas as pd
import seaborn as sns

### **Load the file using pandas.**

In [97]:
df = pd.read_csv("drug200(DT).csv")

### **Perform some basic EDA like peeking top and bottom rows ,checking types of columns, viewing columns**

In [98]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

### **Count which gender is present most in the  dataset**

In [99]:
df['Sex'].value_counts()

Sex
M    104
F     96
Name: count, dtype: int64

### **Plot a bar chart showing counts of each category in the Sex column using Seaborn with the Set2 color palette.**

In [100]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

### **Plot a countplot showing counts of each category in the Cholesterol column using Seaborn with the Set1 color palette.**

In [101]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

le = LabelEncoder()
df['BP'] = le.fit_transform(df['BP'])

le = LabelEncoder()
df['Cholesterol'] = le.fit_transform(df['Cholesterol'])

joblib.dump(le, 'label_encoder.joblib')

['label_encoder.joblib']

### Let's plot a heatmap to visualize how all numerical features in the dataset are correlated with each other

In [102]:
df.head()

   Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    0   0            0   25.355  drugY
1   47    1   1            0   13.093  drugC
2   47    1   1            0   10.114  drugC
3   28    0   2            0    7.798  drugX
4   61    0   1            0   18.043  drugY

In [103]:
X = df.drop('Drug', axis=1)
y = df['Drug']

### Encoding Categorical Variables

We use `LabelEncoder`from sklearn.preprocessing to **convert categorical text columns into numeric values**, which allows machine learning models to process them.

In [104]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [105]:
dt = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=None,
    random_state=42
)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [106]:
import joblib

joblib.dump(dt, 'decision_tree_model.joblib')
joblib.dump(le, 'label_encoder.joblib')

['label_encoder.joblib']

In [107]:
df.head()

   Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    0   0            0   25.355  drugY
1   47    1   1            0   13.093  drugC
2   47    1   1            0   10.114  drugC
3   28    0   2            0    7.798  drugX
4   61    0   1            0   18.043  drugY

In [108]:
from sklearn.metrics import classification_report

y_pred = dt.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       drugA       1.00      1.00      1.00         6
       drugB       1.00      1.00      1.00         3
       drugC       1.00      1.00      1.00         5
       drugX       1.00      1.00      1.00        11
       drugY       1.00      1.00      1.00        15

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

In [109]:
from sklearn import tree

print(tree.export_text(dt, feature_names=list(X.columns)))

|--- Na_to_K <= 14.83
|   |--- BP <= 0.50
|   |   |--- Age <= 50.50
|   |   |   |--- class: drugA
|   |   |--- Age >  50.50
|   |   |   |--- class: drugB
|   |--- BP >  0.50
|   |   |--- BP <= 1.50
|   |   |   |--- Cholesterol <= 0.50
|   |   |   |   |--- class: drugC
|   |   |   |--- Cholesterol >  0.50
|   |   |   |   |--- class: drugX
|   |   |--- BP >  1.50
|   |   |   |--- class: drugX
|--- Na_to_K >  14.83
|   |--- class: drugY